### PR TITLE
Fix ClickHouse outage crashing all dashboard pages

### LINKED ISSUE #145: If Clickhouse is down, it brings down all of Coop
`allRuleInsights` query in the Overview/Dashboard runs on every page load and throws `ECONNREFUSED` if ClickHouse is unavailable. This should fail gracefully (return empty data) instead of crashing the Apollo client. Every page becomes unusable even though ClickHouse is only needed for analytics.

Image

### PR DESCRIPTION
**Pull request by juanmrad**
## Context & Requests for Reviewers

Fixes #145. When ClickHouse is down, every dashboard page crashed because analytics query errors propagated uncaught through resolvers and client components.

Added better handling of the clickhouse error. Also added a lightweight checker for health on clickhouse so we can properly show that the db is down.

Open to suggestions on the error messages there.

Screenshot 2026-03-24 at 8 37 29 PM

### CODE REVIEW

File: server/graphql/resolvers.ts [hunk 1]
```diff
@@ -98,8 +98,25 @@ const Query: GQLQueryResolvers = {
...
 
-    // TODO: this response type actually isn't right; remove cast and fix errors.
-    return context.dataSources.ruleAPI.getAllRuleInsights(user.orgId) as any;
+    try {
+      // TODO: this response type actually isn't right; remove cast and fix errors.
+      return (await context.dataSources.ruleAPI.getAllRuleInsights(
+        user.orgId,
+      )) as any;
+    } catch {
+      return null;
```
Comment (vinaysrao1) [inline server/graphql/resolvers.ts]: empty catch?

File: server/graphql/resolvers.ts [hunk 2]
```diff
@@ -98,8 +98,25 @@ const Query: GQLQueryResolvers = {
...
+  },
+  async isWarehouseAvailable(_, __, context) {
+    try {
+      await context.services.DataWarehouse.query(
+        'SELECT 1',
+        context.services.Tracer,
+      );
+      return true;
+    } catch {
+      return false;
```
Comment (vinaysrao1) [inline server/graphql/resolvers.ts]: Same as above

**Review by vinaysrao1 — APPROVED** [review]
nits about try - catch.
